COUNTRY_CHOICES = [
    ('', 'Select Country'),
    ('US', 'United States'),
    ('CA', 'Canada'),
    ('GB', 'United Kingdom'),
    ('DE', 'Germany'),
    ('FR', 'France'),
    ('IT', 'Italy'),
    ('ES', 'Spain'),
    ('NL', 'Netherlands'),
    ('SE', 'Sweden'),
    ('NO', 'Norway'),
    ('FI', 'Finland'),
    ('DK', 'Denmark'),
    ('IE', 'Ireland'),
    ('BE', 'Belgium'),
    ('CH', 'Switzerland'),
    ('AT', 'Austria'),
    ('GR', 'Greece'),
    ('CZ', 'Czech Republic'),
    ('HU', 'Hungary'),
    ('IN', 'India'),
    ('CN', 'China'),
    ('JP', 'Japan'),
    ('KR', 'South Korea'),
    ('SG', 'Singapore'),
    ('MY', 'Malaysia'),
    ('TH', 'Thailand'),
    ('VN', 'Vietnam'),
    ('PH', 'Philippines'),
    ('ID', 'Indonesia'),
    ('AE', 'United Arab Emirates'),
    ('SA', 'Saudi Arabia'),
    ('AU', 'Australia'),
    ('NZ', 'New Zealand'),
]


COUNTRY_DICT = dict(COUNTRY_CHOICES)
