# Generated by Django 5.2 on 2025-04-30 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_rename_ocassion_product_occasion_alter_fabric_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="main_category",
        ),
    ]
