# Generated by Django 5.2 on 2025-04-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_remove_product_category_remove_product_main_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="fabric",
        ),
        migrations.DeleteModel(
            name="Fabric",
        ),
    ]
