# Generated by Django 5.2 on 2025-05-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_remove_product_fabric_delete_fabric"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="subcategory",
            new_name="sub_category",
        ),
    ]
