# Generated by Django 5.2 on 2025-05-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_alter_maincategory_options_maincategory_name_order"),
        ("store", "0005_rename_subcategory_product_sub_category"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="store_produ_name_a8d7f7_idx",
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["id", "slug"], name="store_produ_id_2abda1_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="store_produ_name_5e57da_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-created_at"], name="store_produ_created_0fbdf8_idx"
            ),
        ),
    ]
