# Generated by Django 5.2 on 2025-05-03 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_alter_maincategory_options_maincategory_name_order"),
        ("store", "0006_remove_product_store_produ_name_a8d7f7_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sub_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="category.subcategory",
            ),
        ),
    ]
