# Generated by Django 5.2 on 2025-05-04 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_productgroup_product_group_productimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
