# Generated by Django 5.2 on 2025-05-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_productimage_options_productimage_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="countdown_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
