# Generated by Django 5.2 on 2025-05-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_productvariation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPiece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Product Piece",
                "verbose_name_plural": "Product Pieces",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="pieces",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="store.productpiece"
            ),
        ),
    ]
