# Generated by Django 5.2 on 2025-05-17 16:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_productpiece_product_pieces"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
