# Generated by Django 5.2 on 2025-05-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpiece",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
