# Generated by Django 5.2 on 2025-05-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_productpiece_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpiece",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
