# Generated by Django 5.2 on 2025-05-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_alter_productpiece_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="delivery_days",
            field=models.PositiveIntegerField(default=7),
        ),
    ]
