# Generated by Django 5.2 on 2025-06-08 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0004_alter_usermeasurement_photo_back_and_more"),
        ("store", "0019_product_delivery_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="measurement.producttype",
            ),
        ),
    ]
