# Generated by Django 5.2 on 2025-06-23 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0022_reviewreply"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewrating",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_reviews",
                to="store.reviewrating",
            ),
        ),
    ]
