# Generated by Django 5.2 on 2025-06-25 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_materialcareitem_productfeature"),
    ]

    operations = [
        migrations.CreateModel(
            name="PieceSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                ("value", models.CharField(max_length=120)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "piece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="store.productpiece",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="piece_specs",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Piece Specification",
                "verbose_name_plural": "Piece Specifications",
                "ordering": ["piece__name", "order"],
            },
        ),
    ]
