# Generated by Django 5.2 on 2025-06-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0028_alter_product_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="color",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
