# Generated by Django 5.2 on 2025-06-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0030_fill_null_brand_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="color",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
