# Generated by Django 5.2 on 2025-06-27 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0031_alter_brand_slug_alter_color_slug"),
        ("store", "0032_fill_null_color_slugs"),
    ]

    operations = []
