# Generated by Django 5.2 on 2025-06-27 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0006_subcategory_image_alter_category_image"),
        ("store", "0033_merge_20250628_0150"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="category.category",
            ),
        ),
    ]
