# Generated by Django 5.2 on 2025-06-27 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0034_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
    ]
