# Generated by Django 5.2 on 2025-06-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0035_remove_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum total weight (kg) for this fee to apply",
                        max_digits=6,
                    ),
                ),
                (
                    "max_weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum total weight (kg) for this fee to apply",
                        max_digits=6,
                    ),
                ),
                (
                    "min_fee",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum shipping fee charged",
                        max_digits=6,
                    ),
                ),
                (
                    "fee_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Additional fee charged per kg within the weight range",
                        max_digits=6,
                    ),
                ),
                (
                    "flat_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Flat fee charged regardless of weight",
                        max_digits=6,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Weight of the product in kg",
                max_digits=6,
            ),
        ),
    ]
