# Generated by Django 5.2 on 2025-05-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TargetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="variationtype",
            name="target_items",
            field=models.ManyToManyField(
                related_name="variation_types", to="variation.targetitem"
            ),
        ),
    ]
