# Generated by Django 5.2 on 2025-05-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variation", "0002_targetitem_variationtype_target_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="variationoption",
            name="included_by_default",
            field=models.BooleanField(default=False),
        ),
    ]
