# Generated by Django 5.2 on 2025-05-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variation", "0004_variationoption_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="variationoption",
            name="price_difference",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
