# Generated by Django 5.2 on 2025-06-30 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="usage_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum redemptions (blank\u202f=\u202funlimited).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="used_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount",
            field=models.IntegerField(
                help_text="Percentage value (0\u202f–\u202f100).",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
