# Generated by Django 5.2 on 2025-06-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0002_coupon_usage_limit_coupon_used_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="stripe_id",
            field=models.CharField(
                blank=True, help_text="Stripe coupon ID", max_length=255, null=True
            ),
        ),
    ]
