# Generated by Django 5.2 on 2025-04-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, upload_to="category/%Y/%m/%d"),
        ),
    ]
