# Generated by Django 5.2 on 2025-05-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_category_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maincategory",
            options={
                "ordering": ["name_order", "name"],
                "verbose_name": "main category",
                "verbose_name_plural": "main categories",
            },
        ),
        migrations.AddField(
            model_name="maincategory",
            name="name_order",
            field=models.IntegerField(default=0),
        ),
    ]
