# Generated by Django 5.2 on 2025-06-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0004_category_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="maincategory",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="main_categories/%Y/%m/%d/"
            ),
        ),
    ]
