# Generated by Django 5.2 on 2025-06-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0005_maincategory_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="sub_categories/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="categories/%Y/%m/%d/"
            ),
        ),
    ]
