# Generated by Django 5.2 on 2025-06-18 20:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_postimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="body",
        ),
        migrations.AddField(
            model_name="post",
            name="description",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="postimage",
            name="image",
            field=models.ImageField(upload_to="blog_images/%Y/%m/%d/"),
        ),
    ]
