# Generated by Django 5.2 on 2025-06-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_post_body_post_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postimage",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="postimage",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
