# Generated by Django 5.2 on 2025-06-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_postimage_options_postimage_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                max_length=250, unique=True, unique_for_date="publish"
            ),
        ),
    ]
