# Generated by Django 5.2 on 2025-05-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeslider",
            name="url",
            field=models.CharField(blank=True, default="/store/shop/", max_length=255),
        ),
    ]
