# Generated by Django 5.2 on 2025-05-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_homeslider_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeslider",
            name="button_text",
            field=models.CharField(
                blank=True, default="Shop Collection", max_length=50
            ),
        ),
    ]
