# Generated by Django 5.2 on 2025-05-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homeslider_button_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homeslider",
            options={"ordering": ["order", "-created_at"]},
        ),
        migrations.AddField(
            model_name="homeslider",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
