# Generated by Django 5.2 on 2025-05-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_lookbook"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookbook",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
