# Generated by Django 5.2 on 2025-05-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_lookbook_is_active"),
        ("store", "0018_alter_productpiece_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopGram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("image", models.ImageField(upload_to="shopgram/%Y/%m/%d/")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="shopgram_posts", to="store.product"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
