# Generated by Django 5.2 on 2025-06-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_shopgram"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shopgram",
            options={"ordering": ["order", "-created_at"]},
        ),
    ]
