# Generated by Django 5.2 on 2025-05-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="customizations",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
