# Generated by Django 5.2 on 2025-05-25 18:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cartitem_customizations"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("300.00"), max_digits=10
                    ),
                ),
                (
                    "gift_wrap_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.00"), max_digits=10
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart Setting",
                "verbose_name_plural": "Cart Settings",
            },
        ),
    ]
