# Generated by Django 5.2 on 2025-05-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_cartsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="base_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="selected_options",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
