# Generated by Django 5.2 on 2025-05-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_cartitem_base_price_cartitem_selected_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="cart_id",
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
