# Generated by Django 5.2 on 2025-06-08 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_cart_last_updated_alter_cart_cart_id_and_more"),
        ("measurement", "0004_alter_usermeasurement_photo_back_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="frozen_measurement_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="user_measurement",
            field=models.ForeignKey(
                blank=True,
                help_text="Measurement set used for this item",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="measurement.usermeasurement",
            ),
        ),
    ]
