# Generated by Django 5.2 on 2025-06-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_cartitem_gift_wrap_cartitem_user_alter_cartitem_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
