# Generated by Django 5.2 on 2025-06-25 20:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_appointment_preferred_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staticpage",
            name="content",
            field=ckeditor.fields.RichTextField(verbose_name="Content"),
        ),
    ]
