# Generated by Django 5.2 on 2025-06-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0013_alter_staticpage_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticpage",
            name="show_in_navbar",
            field=models.BooleanField(
                default=True, help_text="If checked, show in navbar"
            ),
        ),
    ]
