# Generated by Django 5.2 on 2025-06-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0014_staticpage_show_in_navbar"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("youtube", "YouTube"),
                            ("tiktok", "TikTok"),
                            ("pinterest", "Pinterest"),
                            ("custom", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "icon_class",
                    models.CharField(
                        help_text="Font Awesome class, e.g. 'fa fa-facebook' or custom SVG class.",
                        max_length=100,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("visible", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
