# Generated by Django 5.2 on 2025-06-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_stripe_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
