# Generated by Django 5.2 on 2025-06-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_shipping_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="gift_wrap_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
