# Generated by Django 5.2 on 2025-06-30 17:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_gift_wrap_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Discount amount applied to this order",
                max_digits=10,
            ),
        ),
    ]
