# Generated by Django 5.2 on 2025-06-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measurementtype",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AddField(
            model_name="measurementtype",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Controls display order"
            ),
        ),
    ]
