# Generated by Django 5.2 on 2025-06-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0002_alter_measurementtype_options_measurementtype_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermeasurement",
            name="name",
        ),
        migrations.AddField(
            model_name="usermeasurement",
            name="fit_type",
            field=models.CharField(
                choices=[
                    ("tailor", "Tailored Fit"),
                    ("slim", "Slim Fit"),
                    ("comfortable", "Comfortable Fit"),
                ],
                default="tailor",
                help_text="Select the fit type for this measurement set.",
                max_length=20,
            ),
        ),
    ]
