# Generated by Django 5.2 on 2025-06-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0003_remove_usermeasurement_name_usermeasurement_fit_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermeasurement",
            name="photo_back",
            field=models.ImageField(
                blank=True, null=True, upload_to="measurements/photos/%y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="usermeasurement",
            name="photo_front",
            field=models.ImageField(
                blank=True, null=True, upload_to="measurements/photos/%y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="usermeasurement",
            name="photo_side",
            field=models.ImageField(
                blank=True, null=True, upload_to="measurements/photos/%y/%m/%d/"
            ),
        ),
    ]
